### ISSUE TITLE
Unreadable Transmission and Application Options Page in 4K Monitor

### ISSUE THREAD

**Issue by rheinon** [xavery/transgui#103]
Like what the subject says.  This is from a 3840 x 2160 monitor resolution in v5.18.6.f:

![2024-08-26 17_39_44-Application options](https://github.com/user-attachments/assets/229f77fc-a6b6-4903-8d4a-0e9b8adba125)

**Comment by lighterowl** [comment]
Hi, thanks.

This is bad.

**Comment by lighterowl** [comment]
Things are looking much better now. I should've caught this myself but my everyday setup is a single 1440p monitor running at 96dpi. The main reason behind this mess is the removal of BaseForm in e6ca4982b441f278561330dcc54ba88a83bcaa40 which included custom scaling code.

With the changes made now, I'm _reasonably_ sure that we're relying on Lazarus completely when it comes to scaling, which is a very good thing as its support for this seems to be rather okay. I tested these changes on MacOS with 150% scaling and Windows with 300% scaling.

https://wiki.lazarus.freepascal.org/High_DPI provides a good overview of how scaling works in Lazarus. The `tl;dr` is "make sure font size is specified explicitly" which is what the fix was going to be originally. However, transgui being transgui, there were surprises on the way, as the changes caused the "Application options" window to suddenly become enormous on non-96dpi screens with giant spaces between widgets in some of the tabs. I tracked this down to the fact that this window reused the code from the "Connection options" form by creating it as hidden and stealing its tabs. This must've confused the scaling/sizing code because stuff seems to work okay with every tab as a separate frame at code level.

This change also opens the door to enabling `PerMonitorV2` on Windows. I tested this during development and things "worked" as in "scaled correctly" when moving the window between monitors but some transgui's behaviour needs further investigation so I ended up leaving this at the current setting, which means the application will be drawn with the DPI of the main display and bitmap-scaled on others. I'll probably end up creating a separate ticket about this.

**Comment by lighterowl** [comment]
![screenshot](https://github.com/user-attachments/assets/cfa71a3e-b495-43ed-8505-f02f99d6058b)

**Comment by SESNut** [comment]
I am using 3440x1440 and now the main window is really small and text scaling has no effect, neither does any of the high dpi settings in the compatibility options. Does the app need its own font settings now since it unaffected by windows scaling?
![Screenshot 2024-09-22 022841](https://github.com/user-attachments/assets/620e96e6-7b7f-4d45-a88f-0ac74a45fbd3)

**Comment by lighterowl** [comment]
> Does the app need its own font settings now since it unaffected by windows scaling?

No. The screenshot I posted earlier was taken with scaling set to 300% in "Display settings", nothing more.

**Comment by SESNut** [comment]
I dont use display scaling since i dont need my windows larger but I do use text scaling and it seems to have no effect on the fonts

**Comment by lighterowl** [comment]
> I dont use display scaling since i dont need my windows larger but I do use text scaling and it seems to have no effect on the fonts

Which Windows setting is that, precisely?

**Comment by SESNut** [comment]
![Screenshot 2024-09-22 042158](https://github.com/user-attachments/assets/dc7f2a9f-8900-49a8-a017-a74b8a4efc86)

**Comment by lighterowl** [comment]
Yep, this is totally ignored by transgui yet the Lazarus IDE does take this into account as its font gets bigger when I change this setting.

"Stock" LCL-based applications don't honour this setting either so there must be some custom code inside Lazarus IDE to handle it.

**Comment by pwinnski** [comment]
Absolutely fantastic work!
