### ISSUE TITLE
Selected count in status bar doesn't work 

### ISSUE THREAD

**Issue by wally-crunk** [xavery/transgui#47]
The "selected" count in the status bar is meant to add-up the size of highlighted (selected) torrents, but it displays a fixed value.

Tested:  5.18.2.f, 5.18.3.f,   mac os 13.4.1 (c)

**Comment by wally-crunk** [comment]
Specifically, it appears to be showing the size of the visible "filtered" torrents (chosen by clicking in the Left-hand side bar, e.g., when you click a directory, the status-bar will update with the sum of the torrents in that folder location.)

However, selecting (highlighting) line-items does not update the sum and override the filtered sum.

 I thought the 'parent' project transgui did this.

It is confusing that it says "selected" but shows "filtered".   It would be more clear and useful if either:

(1) both "filtered" and "selected" sums were shown, or
(2) the "selected" sum overrides "filtered" sum, or best yet,
(3) the status bar message uses the word "Filtered" or "Visible", like "Filtered: 444 MB" and changes to "Selected: 35 MB" when the user highlights (selects) row(s).

**Comment by xavery** [comment]
The bug itself is caused by an off-by-one error when accessing the array of displayed/selected torrents. Apparently it must've worked with the earlier `fpc` version that the "parent" transgui project uses, now it causes an exception which is "conveniently" swallowed by the code and results in the status bar text remaining unchanged.

I think we can use this chance to redo the naming of these labels, as it made me confused myself :
* `Total` is just the sum of all torrents' sizes, ignoring how many files inside them were actually selected to be downloaded,
* `Selected` is the sum of sizes all files inside the torrents which were actually *selected* for download,
* `Downloaded` is the sum of the number of bytes actually downloaded,
* `Remain` is essentially `Selected - Downloaded`.

So it doesn't make sense to change `Selected` to `Filtered`. If anything, it's `Total` that should either be `Selected` or `Filtered` (since all the following sizes refer to either selected or filtered torrents), but then what should the current `Selected` be called? The only thing that comes to mind is `Target` which isn't perfect.

**Comment by xavery** [comment]
#48 fixes the bug with not updating, #50 updates the status bar so that it removes `Total` and what's currently `Selected` becomes either `Filtered` and `Selected` depending on whether there's a selection in the list.

Please reopen if you'd like this to be implemented differently.

**Comment by wally-crunk** [comment]
I think that sounds good.  Sorry, I didn't see this sooner.  'Filtered' should be really great, thanks!
