### ISSUE TITLE
Double-clicking on the separator item in the status/folder/tracker/label filter list hangs the application

### ISSUE THREAD

**Issue by Tharn** [xavery/transgui#74]
I dunno if this happens with older versions of the daemon, but connecting to 4.0.5 on Windows 10, same machine, I can reliably make TRGUI hang by double clicking on this line underneath the default torrent lists.

![trgui2](https://github.com/xavery/transgui/assets/13466852/0028cf5f-3ea7-4c70-8f3f-176783b1fb82)

Anyone else getting this?

When the daemon is populated, clicking on these separators seems to flick the 'activity' cursor above and below the separator. Which is also a little weird behavior, but at least there are no hangs.

**Comment by lighterowl** [comment]
Thanks for the report.

I can reliably reproduce this as well, however this only seems to happen when connecting to a daemon with zero torrents, like in your screenshot. Doesn't seem to be related to the version of the daemon though as I reproduced this with 2.94 too.

**Comment by lighterowl** [comment]
Fixed in https://github.com/lighterowl/transgui/commit/57790475738e07f905df11b7e4d7e5d2686d00b5.

The behaviour you described was actually explicitly programmed, and this commit removes that as I have no idea what it was supposed to achieve and caused an infinite loop when the two separator items were next to each other. Clicking on a separator item from now on will always move to the row above it.
