### ISSUE TITLE
Expose the hidden "Quick Verify" behavior (?)

### ISSUE THREAD

**Issue by wally-crunk** [xavery/transgui#81]
Transmission + transgui has a "feature" that's easy to miss.

— Say the files are already downloaded and available on the host machine.
— Add a .torrent file to Transgui, and in the **first** dialog, provide the correct directory name where the files CURRENTLY ARE, and hit ok. 
— (Transmission + transgui) recognizes the files are there and immediately lists them as "100%" -- no actual verify is performed or required.   You can seed immediately.

Any other time **_after_** this first dialog box (afaik), you can set the folder-name where the files CURRENTLY ARE, and hit ok, but they are listed as "0% complete" and a full 'Verify' must be performed.

I don't know if this is behavior of the underlying daemon or something the transgui does.  Is there anything that can be done, to expose this bypassing of the Verify step?

**Comment by wally-crunk** [comment]
On further look:

— The "quick verify" (or if you prefer, _no verify_) must be done by transmission-daemon, as it also works in the transmission-daemon's Watch folder, even if transgui is not involved.

— Is there a way for transgui to access that on the daemon, and bypass the requirement to verify?

**Comment by lighterowl** [comment]
This is a daemon feature that was added in 4.0. Here's the relevant PR : https://github.com/transmission/transmission/pull/4611 and https://github.com/transmission/transmission/pull/2626 contains some more information around this.

It's not "quick verify" but "lazy verify" which allows starting the torrent immediately and verifying the data while it's being seeded, and any bad data will cause it to drop to "Downloading" state. Not sure if there's anything to be done in transgui about this, since this is a `settings.json` setting only which isn't even exposed via RPC.

**Comment by wally-crunk** [comment]
Thank you for the reply @xavery, much appreciated
