### ISSUE TITLE
.torrent file association does not work in macOS Sequoia

### ISSUE THREAD

**Issue by plughie** [xavery/transgui#95]
I'm running MacOS Sequoia beta, and when I try to open a torrent file from the finder with transgui, I get a message that refuses to open it for any reason other than to accept not opening or deleting the torrent file. Torrents associate properly to Transmission, but not transgui. I can use the File/Open dialog to open torrents without issue.

**Comment by lighterowl** [comment]
No promises as this sounds pretty OS-specific. Also, I don't have access to MacOS Sequoia.

**Comment by lighterowl** [comment]
Ok, some digging led me to a ticket which I think is most relevant to this : https://github.com/qutebrowser/qutebrowser/issues/7306 . `tl;dr` transgui's `Info.plist` uses the `CFBundleTypeOSTypes` key to declare the file extensions it supports. Doing that has apparently been [deprecated since OSX 10.5](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-101685) but Sequoia must've finally pulled the plug.

The "new" way to do this seems to be declaring an array of [`LSItemContentTypes` strings](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundledocumenttypes/lsitemcontenttypes?language=objc), each of which represent a ["Uniform Type Identifier"](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_intro/understand_utis_intro.html) that the application supports. Now, it doesn't seem like there's an OS-wide UTI for torrent files, so [Transmission's Info.plist](https://github.com/transmission/transmission/blob/main/macosx/Info.plist) uses the [`UTExportedTypeDeclarations`](https://developer.apple.com/documentation/bundleresources/information_property_list/utexportedtypedeclarations?language=objc) key to declare it and call itself the owner of that type.

I also found https://github.com/holzschu/Carnets/issues/27 whose author says this :

> iOS doesn't handle clashing of different UTIs declared for same file extensions well. It seems that under current implementation of file handling in iOS, if another app claims notebook extension with a different UTI, both Juno and Carnets may not be able to open notebooks at all, or at least so my tests show.

So perhaps we'll just end up copy-and-pasting Transmission's declarations into transgui's so that both applications can still be used to open torrent files. It looks like [qBittorrent does the same thing](https://github.com/qbittorrent/qBittorrent/blob/master/dist/mac/Info.plist), anyway.

**Comment by lighterowl** [comment]
@plughie Can you try this build? https://github.com/lighterowl/transgui/actions/runs/10376929473/artifacts/1808607169

**Comment by lighterowl** [comment]
@plughie Any news?
